// previous lines...

  const insertMessageMutation = gql`\n    mutation insertMessage($input: InsertMessageInput!) {\n      insert_messages_one(object: $input) {\n        id\n        content\n        room_id: \\"room-livreurs\\"\n      }\n    }\n  `; // Updated here to add room_id field\n
// subsequent lines...