/* eslint-disable no-restricted-globals */
/// <reference lib="webworker" />

import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite (defensive check)
const manifest = self.__WB_MANIFEST;
if (manifest && Array.isArray(manifest) && manifest.length > 0) {
  precacheAndRoute(manifest);
} else {
  console.warn('[Service Worker] No precache manifest found, skipping precache.');
}

// Clean up outdated caches automatically
cleanupOutdatedCaches();

// Force immediate activation of new service worker
self.addEventListener('install', () => {
  self.skipWaiting();
});

// Firebase messaging background handler
self.addEventListener('push', (event: PushEvent) => {
  console.log('[Service Worker] Push received:', event);

  if (!event.data) {
    console.log('[Service Worker] Push event but no data');
    return;
  }

  let notificationData;
  try {
    notificationData = event.data.json();
  } catch (error) {
    console.error('[Service Worker] Error parsing push data:', error);
    notificationData = {
      notification: {
        title: 'EasyFlows Pro',
        body: event.data.text() || 'Nouvelle notification',
      },
    };
  }

  const { notification, data } = notificationData;
  const title = notification?.title || 'EasyFlows Pro';
  const options = {
    body: notification?.body || '',
    icon: '/pwa-192x192.svg',
    badge: '/pwa-192x192.svg',
    data: data || {},
    vibrate: [200, 100, 200],
    tag: data?.type || 'general',
    requireInteraction: false,
  };

  event.waitUntil(
    self.registration.showNotification(title, options)
  );
});

// Handle notification click
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  console.log('[Service Worker] Notification clicked:', event);

  event.notification.close();

  const urlToOpen = event.notification.data?.link || '/';

  event.waitUntil(
    (async () => {
      // Get all clients (open windows/tabs)
      const clientList = await self.clients.matchAll({
        type: 'window',
        includeUncontrolled: true,
      });

      // Check if there's already a window/tab open
      for (const client of clientList) {
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }

      // If no window/tab is open, open a new one
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })()
  );
});

// Handle messages from the client
self.addEventListener('message', (event: ExtendableMessageEvent) => {
  console.log('[Service Worker] Message received:', event.data);

  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Clean up old caches
self.addEventListener('activate', (event: ExtendableEvent) => {
  console.log('[Service Worker] Activating...');
  
  event.waitUntil(
    (async () => {
      // Enable navigation preload if supported
      if ('navigationPreload' in self.registration) {
        await self.registration.navigationPreload.enable();
      }

      // Claim all clients
      await self.clients.claim();
    })()
  );
});
